# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='leopard.jpg', upload_to='images')),
                ('img_name', models.CharField(default='My Photo', max_length=30)),
                ('img_caption', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
