# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0003_auto_20190521_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='image',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='image',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='image',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post_vote',
            name='voted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.Image'),
        ),
        migrations.AddField(
            model_name='post_vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='post_vote',
            unique_together=set([('voter', 'voted')]),
        ),
    ]
