# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20190521_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Vote',
            new_name='Image_Vote',
        ),
    ]
