# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20190521_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='image_vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='image_vote',
            name='voted',
        ),
        migrations.RemoveField(
            model_name='image_vote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='image',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='image',
            name='up_vote',
        ),
        migrations.DeleteModel(
            name='Image_Vote',
        ),
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.Image'),
        ),
    ]
